blank_issues_enabled: false
contact_links:
  - name: Colack
    url: https://email:uniformkitten281@gmail.com/
    about: Please ask and answer questions here.
  - name: Discord Server
    url: https://discord.com/invite/CUJrdW5vKn
    about: Please report security vulnerabilities here.
